---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build
  image: golang:1.13.0
  commands:
  - sh scripts/build.sh
  environment:
    GOARCH: amd64
    GOOS: linux
  when:
    branch: master

# - name: publish
#   image: plugins/docker:18
#   settings:
#     auto_tag: true
#     auto_tag_suffix: linux-amd64
#     dockerfile: docker/Dockerfile.server.linux.amd64
#     repo: drone/drone
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#   when:
#     branch: master
